name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/spring-petclinic-rest/spring-petclinic-rest/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
      - run: touch starting_build_uses-checkout_15
      - run: rm starting_build_uses-checkout_15
      - uses: actions/checkout@v2
      - run: touch starting_build_SetupJDK11_16
      - run: rm starting_build_SetupJDK11_16
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - run: touch starting_build_BuildwithMaven_22
      - run: rm starting_build_BuildwithMaven_22
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'UT-SE-Research'
          destination-repository-name: 'ci-analyzes'
          target-branch: '1676917386-c0ae930'
          target-directory: 'spring-petclinic-rest/.github/workflows/maven-build/build'
        continue-on-error: true
      - name: Check push directory exit code
        if: steps.push_directory.outcome == 'failure'
        run: |
          echo 'push failed, trying pull and then push'
          git config --global user.name 'UT-SE-Research'
          git add .
          git commit -m 'report ${{ github.head_ref }}'
          while ! git push origin {time}; do
            git pull --rebase https://github.com/UT-SE-Research/ci-analyzes.git 1676917386-c0ae930
            git push https://github.com/UT-SE-Research/ci-analyzes.git HEAD:1676917386-c0ae930
          done
