name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
          pip install inotify
      - run: sudo apt update
      - uses: actions/checkout@v2
      - run: python .github/workflows/inotify_script.py /home/runner/work/spring-petclinic-rest/spring-petclinic-rest /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
      - run: touch starting_build_uses-checkout_15
      - run: rm starting_build_uses-checkout_15
      - uses: actions/checkout@v2
      - run: touch starting_build_SetupJDK11_16
      - run: rm starting_build_SetupJDK11_16
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - run: touch starting_build_BuildwithMaven_22
      - run: rm starting_build_BuildwithMaven_22
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: rat check
        if: always()
        run: |
           if [ -f /home/runner/work/spring-petclinic-rest/spring-petclinic-rest/target/rat.txt ]; then cat /home/runner/work/spring-petclinic-rest/spring-petclinic-rest/target/rat.txt; fi
      - name: Check script file exists and execute
        if: always()
        run: |
          [ -f .github/workflows/script.py ] && python .github/workflows/script.py
          [ -f /home/runner/work/spring-petclinic-rest/spring-petclinic-rest/optimizing-ci-builds-ci-analysis/job.csv ] || mkdir -p /home/runner/work/spring-petclinic-rest/spring-petclinic-rest/optimizing-ci-builds-ci-analysis/; echo "${GITHUB_RUN_ID},${GITHUB_JOB},spring-petclinic-rest,${GITHUB_WORKFLOW}" > /home/runner/work/spring-petclinic-rest/spring-petclinic-rest/optimizing-ci-builds-ci-analysis/job.csv
      - name: Checkout to destination CI-analyzes repo
        uses: actions/checkout@v3
        if: always()
        with:
          path: spring-petclinic-rest
          ref: '1691374686-548a464'
          repository: 'UT-SE-Research/ci-analyzes'
          token: '${{ secrets.API_TOKEN_GITHUB }}'
          persist-credentials: true
      - name: Copy files to push to another directory
        if: always()
        run: |
          mkdir -p spring-petclinic-rest/spring-petclinic-rest/.github/workflows/maven-build/build
          cp -rvT optimizing-ci-builds-ci-analysis spring-petclinic-rest/spring-petclinic-rest/.github/workflows/maven-build/build
      - run: echo https://github.com/UT-SE-Research/ci-analyzes/tree/1691374686-548a464/spring-petclinic-rest/.github/workflows/maven-build/build
      - name: Pushes analysis to another repository
        if: always()
        working-directory: spring-petclinic-rest
        run: |
          commit_message=$GITHUB_REPOSITORY@$GITHUB_WORKFLOW_SHA
          git config --global user.name 'UT-SE-Research'
          git config --global user.email '${{ secrets.EMAIL }}'
          git add .
          git commit -m $commit_message
          while ! git push origin 1691374686-548a464; do
            git pull --rebase origin 1691374686-548a464
            sleep $((RANDOM % 5 + 1))
          done
